#
# Automatically generated file; DO NOT EDIT.
# crosslinux-0.0.3 -- Configure a Cross Linux Build
#

#
# System Name and Version
#
CONFIG_BRAND_NAME="ttylinux"
CONFIG_BRAND_URL="http://www.ttylinux.net/"
CONFIG_RELEASE_NAME="athling"
CONFIG_RELEASE_VERS="2014.10"

#
# System Architecture and Boot Configuration
#
# CONFIG_BOARD_BEAGLEBONE is not set
# CONFIG_BOARD_MAC_G4 is not set
# CONFIG_BOARD_PC_486 is not set
# CONFIG_BOARD_PC_686 is not set
CONFIG_BOARD_PC_X86_64=y
CONFIG_BOARD="pc_x86_64"
CONFIG_CPU_ARCH="x86_64"
CONFIG_LINUX_ARCH="x86_64"
CONFIG_CFLAGS="-m64 -Os"
CONFIG_BOOTLOADER="isolinux"
CONFIG_ROOTFS_INITRD=y
# CONFIG_ROOTFS_INITRAMFS is not set
# CONFIG_ROOTFS_TARBALL is not set
CONFIG_BOOT_EPHEMERAL=y
# CONFIG_BOOT_PERSISTENT is not set
# CONFIG_ROOTFS_EXT2 is not set
CONFIG_ROOTFS_EXT3=y
# CONFIG_ROOTFS_EXT4 is not set
CONFIG_ROOTFS_SIZE_MB=128
CONFIG_MEDIA_ISO9660=y
CONFIG_INCLUDE_MEDIA_ROOT_DOCS=y
CONFIG_INCLUDE_MEDIA_DEBUG_KERNEL=y
CONFIG_INCLUDE_MEDIA_CONFIG_FILES=y
CONFIG_INCLUDE_MEDIA_DOCS=y
CONFIG_INCLUDE_BUILD_LOGS=y
CONFIG_INCLUDE_BIN_PKGS=y
CONFIG_LOADER_SYSLINUX_6p01=y
CONFIG_FORCE_SYSLINUX=y
CONFIG_LOADERSUBDIR="syslinux-6.01"

#
# Cross-tool Chain and Build Configuration
#
CONFIG_XTOOL_NAME="x86_64-generic-linux-gnu"
CONFIG_XTOOL_BIN_DIR="/sda7/cl-meta-dir/x-tools/x86_64-generic-linux-gnu/bin"
CONFIG_XTOOL_TARGET_MANIFEST_DIR="/sda7/cl-meta-dir/x-tools/x86_64-generic-linux-gnu/_target-source"
CONFIG_DOWNLOAD_DIR="/sda7/cl-meta-dir/download"
CONFIG_PARALLEL_JOBS=y
CONFIG_STRIP_BINS=y
CONFIG_SITE_SCRIPTS=y
CONFIG_SITE_KERNEL_CFG=y
CONFIG_SITE_KERNEL_CFG_PNAME="kernel/linux-3.10.2.cfg"
# CONFIG_SITE_KERNEL is not set
CONFIG_FORCE_SITE_KERNEL_CFG=y

#
# Basic System
#
CONFIG_BLD_CROSSLINUX_BASEFS=y
CONFIG_FORCE_BASEFS=y
# CONFIG_BLD_CROSSLINUX_DEVFS is not set
CONFIG_BLD_CROSSLINUX_LIBC=y
CONFIG_FORCE_LIBC=y

#
# Libraries
#
CONFIG_BLD_NCURSES_5p9=y
CONFIG_NCURSES_HAS_LIBS=y
CONFIG_NCURSES_HAS_WIDEC=y
CONFIG_BLD_READLINE_6p3=y
CONFIG_BLD_ALSA_LIB_1p0p28=y
CONFIG_BLD_GMP_5p0p5=y
CONFIG_BLD_MPFR_3p1p1=y
CONFIG_BLD_PPL_0p11=y
CONFIG_BLD_CLOOG_0p16p1=y
CONFIG_BLD_MPC_1p0p1=y

#
# System Programs
#
CONFIG_BLD_UTIL_LINUX_2p24=y
CONFIG_HAVE_UTIL_LINUX=y
CONFIG_BLD_BASH_4p2=y
CONFIG_BLD_BUSYBOX_1p22p1=y
CONFIG_FORCE_BUSYBOX=y
# CONFIG_BUSYBOX_HAS_LOSETUP is not set
CONFIG_BLD_E2FSPROGS_1p42p9=y
# CONFIG_E2FSPROGS_HAS_BLKID is not set
# CONFIG_E2FSPROGS_HAS_FINDFS is not set
CONFIG_BLD_KMOD_16=y
CONFIG_BLD_LILO_24p0=y
CONFIG_BLD_NTFS_3G_NTFSPROGS_2014p2p15=y
CONFIG_BLD_TTYLINUX_UTILS_1p6=y
CONFIG_BLD_UDEV_182=y
CONFIG_FORCE_UDEV=y

#
# Development Tools
#
CONFIG_BLD_BINUTILS_2p23=y
CONFIG_BLD_GCC_4p7p3=y
CONFIG_BLD_MAKE_4p0=y
CONFIG_BLD_CROSSLINUX_LIBC_DEVEL=y
CONFIG_FORCE_LIBC_DEVEL=y

#
# Service Programs
#
CONFIG_BLD_DROPBEAR_2014p63=y
CONFIG_BLD_GPM_1p20p7=y
CONFIG_BLD_IPTABLES_1p4p18=y
# CONFIG_BLD_PPP_2p4p5 is not set
CONFIG_BLD_THTTPD_2p25B=y

#
# Applications
#
CONFIG_BLD_ALSA_UTILS_1p0p28=y
CONFIG_BLD_CALC_2p12p4p13=y
CONFIG_BLD_DTACH_0p8=y
CONFIG_BLD_DVTM_0p11=y
CONFIG_BLD_HASERL_0p9p32=y
CONFIG_BLD_LUA_5p2p3=y
CONFIG_BLD_LYNX_2p8p8=y
CONFIG_BLD_NANO_2p3p2=y
CONFIG_BLD_RETAWQ_0p2p6C=y
CONFIG_RETAWQ_HAS_THREADING=y
